twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    globals:
        supported_locales:  "%env(SUPPORTED_LOCALES)%"
        locale_names:  "%env(LOCALE_NAMES)%"
